before_script:
  - mysql -e 'create database fpcs;'
  - mysql -e 'use fpcs;'
language: cpp
compiler:
  - g++
  - clang++
os:
  - linux
script: ./src/make clean && make
notifications:
  email:
    recipients:
      - h9379203@gmail.com
    on_success: change
    on_failure: always
  slack:
    eliotteam:njCrDCaR1WBjolzJne30fy11
